seed/math/power/addition_chain/shortest/mixed_recursive_greedy_zpow_addition_chain__doc__py_adhoc_call.py;search_star_chain7recursive_shortest.py;shortest_addition_chain__arbitrary_recur_shortest_stem.py..址距溟次形式纟任意纟递归婪溟链.ge38039.le70070.txt.tar.lzma;对称多项式讠基表达.py;input7timeout.py;finger_tree/ft23_7sized_seq.py;ft23_7sized_ascend_set;txz;int_repr7human;int_repr7compact;

diff --git a/bash_script/app/man__save_to_file b/bash_script/app/man__save_to_file
--- a/bash_script/app/man__save_to_file
+++ b/bash_script/app/man__save_to_file
@@ -1,4 +1,74 @@
 
+#######
+#new-version:
+#######
+#@20251128
+#come_from: view ../../python3_src/bash_script/app/info__save_to_file
+
+: <<'EOF__width_control'
+
+man -c -T ascii -O indent=1 -O width=1000 zstdcat
+
+s="$(man -c -T ascii -O indent=1 -O width=1000 zstdcat | tail -n 1)" ; echo ${#s}
+  =>539
+
+EOF__width_control
+
+
+
+
+
+
+exit_status=0
+
+for prog_name ; do
+  #echo "${prog_name}"
+  if ! [[ ${prog_name} =~ ^[[:alnum:]a-zA-Z0-9_.+-]+$ ]] ; then
+    # no space to form a path
+    echo >&2 "${prog_name@Q} is not identifier"
+    exit_status=1
+  fi
+done
+[[ exit_status -eq 0 ]] || exit "${exit_status}"
+
+for prog_name ; do
+  opath="others/app/termux/help/${prog_name}.man.txt"
+  if [[ -a "${opath}" ]] ; then
+    echo "existed: ${opath@Q}" >&2
+  else
+    #.man "${prog_name}" > "${opath}"
+    #
+    #.txt="$(man -c -T ascii -O indent=1 -O width=1000 "${prog_name}")"
+    #
+    txt="$(man -c "${prog_name}")"
+      #ok: nest "" via $()
+    if [[ $? -eq 0 ]] ; then
+      #.cat <<< "${txt}" > "${opath}"
+      man -c "${prog_name}" | col -b -x > "${opath}"
+      #.echo "view ${opath@Q}"
+      echo ":view ${opath}"
+        #no quote for vim cmd
+    else
+      echo >&2 "fail: man ${prog_name@Q}"
+    fi
+  fi
+done
+
+exit
+
+
+
+
+
+
+
+
+
+
+
+#######
+#old-version:
+#######
 prog_name="$@"
 #echo "${prog_name}"
 if ! [[ ${prog_name} =~ ^[[:alnum:]a-zA-Z0-9_.+-]+$ ]] ; then { echo 'prog_name is not identifier' >&2 ; exit 1 ; } ; fi
